name: Linting & Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pytest:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: uv pip install -e .[dev] --system
      - name: Run Pytest
        run: pytest
